sudo: required
language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - echo "deb http://http.us.debian.org/debian unstable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.9 --force-yes -y
  - sudo apt-get install ninja-build -y --force-yes
  - pip install pep8 pyflakes --use-mirrors
install:
  - ./install_meson.py --prefix /tmp
env:
  matrix:
    - STAGE='tests'
    - STAGE='pyflakes'
script:
  - "[ $STAGE = tests ]    || env MESON_PRINT_TEST_OUTPUT=1 ./run_tests.py"
  - "[ $STAGE = pyflakes ] || pyflakes modules tools *.py"
