sudo: required
language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc-4.9 gcc-4.9-locales --force-yes -y
  - curl -sL https://github.com/martine/ninja/releases/download/v1.5.3/ninja-linux.zip > ninja.zip
  - unzip ninja.zip -d /usr/local/bin
  - pip install pep8 pyflakes --use-mirrors
install:
  - ./install_meson.py --prefix /tmp
env:
  matrix:
    - STAGE='tests'
    - STAGE='pyflakes'
script:
  - "[ $STAGE = tests ]    || env MESON_PRINT_TEST_OUTPUT=1 ./run_tests.py"
  - "[ $STAGE = pyflakes ] || pyflakes modules tools *.py"
