sudo: required
language: python
python:
  - "3.3"
  - "3.4"
before_install:
# Update to GCC 4.9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gobjc++-4.9 g++-4.9 gcc-4.9 gcc-4.9-locales --force-yes -y
  - sudo rm -rf /usr/bin/gcc && sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo rm -rf /usr/bin/g++ && sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
  - sudo rm -rf /usr/bin/gobjc++ && sudo ln -s /usr/bin/gobjc++-4.9 /usr/bin/gobjc++
# Install required packages for tests
  - sudo apt-get -qq install libboost-dev libgtest-dev libgnustep-base-dev libwxgtk2.8-dev gobject-introspection --force-yes -y

  - curl -sL https://github.com/martine/ninja/releases/download/v1.5.3/ninja-linux.zip > ninja.zip
  - sudo unzip ninja.zip -d /usr/local/bin

  - pip install pyflakes coverage coveralls --use-mirrors
install:
  - ./install_meson.py --prefix /tmp
env:
  matrix:
    - STAGE='tests'
    - STAGE='pyflakes'
script:
  - if [ $STAGE = 'tests' ]; then env MESON_PRINT_TEST_OUTPUT=1 coverage run ./run_tests.py; fi
  - if [ $STAGE = 'pyflakes' ]; then pyflakes modules tools *.py; fi
after_success:
  - coveralls