sudo: required
language: python
python:
  - "3.3"
  - "3.4"
before_install:
  - echo "deb http://http.us.debian.org/debian testing main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install ninja-build -y
install:
  - pip install pep8 pyflakes --use-mirrors
script:
  - "./install_meson.py --prefix /tmp"
  - "env MESON_PRINT_TEST_OUTPUT=1 ./run_tests.py"
  - "pyflakes modules tools *.py"
